version: "3"
services:
  qr-inventory-front:
    container_name: qr-inventory-front
    restart: unless-stopped
    build:
      context: .
      target: nmgix-dev
    env_file:
      - .env
    ports:
      - "80:80"
    networks:
      - qr-inventory-proxy

# /etc/nginx/conf.d/default.conf
networks:
  qr-inventory-proxy:
    name: qr-inventory
