version: "3"
services:
  qr-inventory-front:
    container_name: qr-inventory-front
    restart: unless-stopped
    build:
      context: .
    env_file:
      - .env
    ports:
      - "443:443"
    networks:
      - qr-inventory-proxy

networks:
  qr-inventory-proxy:
    name: qr-inventory
