name: Деплой фронтенда

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Получение репозитория
        uses: actions/checkout@v3.5.2

      - name: Настройка .env
        run: |
          touch .env
          echo REACT_APP_DOMAIN="${{ vars.REACT_APP_DOMAIN }}" >> .env | 
          echo REACT_APP_API_HOST="${{ vars.REACT_APP_API_HOST }}" >> .env
          echo GENERATE_SOURCEMAP="${{ vars.GENERATE_SOURCEMAP }}" >> .env

      - name: Сборка Docker и деплой
        run: |
          docker-compose build
          docker-compose down 
          docker-compose up -d
