name: Деплой фронтенда и nginx

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Получение репозитория
        uses: actions/checkout@v3.5.2

      - name: Настройка .env
        run: |
          touch .env
          echo REACT_APP_DOMAIN="${{ vars.REACT_APP_DOMAIN }}" >> .env | 
          echo REACT_APP_API_HOST="${{ vars.REACT_APP_API_HOST }}" >> .env
          echo GENERATE_SOURCEMAP="${{ vars.GENERATE_SOURCEMAP }}" >> .env
          echo SSL_CRT_FILE="certificates/your_domain.crt" >> .env
          echo SSL_KEY_FILE="certificates/your_domain.key" >> .env

      - name: Копирование сертификатов
        run: |
          cp ../../../../certificates ./

      - name: Сборка Docker и деплой
        run: |
          docker-compose up --build -d --force-recreate
